# Generated by Django 3.2.5 on 2022-01-20 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffenderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speed', models.IntegerField(default=0)),
                ('is_speeding', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offenders/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
